name: MarkDown to HTML
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - '**.md'
      #- 'docs/images/**'

jobs:
  converttopdf:
    name: Build HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1.2.0
        with:
          input_dir: /
          output_dir: /
          #images_dir: docs/images
          # for example <img src="./images/file-name.png">
          #image_import: ./images
          # Default is true, can set to false to only get PDF files
          build_html: true
      #- uses: actions/upload-artifact@v1
        #with:
          #name: docs
          #path: pdfs
