name: MarkDown to HTML
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    paths:
      - '**.md'
  workflow_dispatch:

jobs:
  converttopdf:
    name: Build HTML
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1.2.0
        with:
          #input_dir: ./
          #output_dir: ./
          build_html: true
      #- uses: actions/upload-artifact@v1
        #with:
          #name: docs
          #path: pdfs
